[phases.setup]
nixPkgs = [
    "php82",
    "php82Packages.composer",
    "nodejs_20",
    "glib",
    "nss",
    "atk",
    "at-spi2-atk",
    "libdrm",
    "libxcomposite",
    "libxdamage",
    "libxrandr",
    "mesa",
    "libxss",
    "alsa-lib",
    "cairo",
    "pango",
    "gdk-pixbuf",
    "gtk3",
    "libxkbcommon",
    "libxshmfence"
]

[phases.install]
cmds = [
    "rm -rf bootstrap/cache/*.php",
    "composer install --no-dev --optimize-autoloader --no-scripts",
    "php artisan package:discover --ansi",
    "npm ci",
    "npm run build"
]

[start]
cmd = "bash .railway/start.sh"

